name: Trigger auto deployment for biolab-capps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/biolab-capps-AutoDeployTrigger-b4bbc238-cfea-44af-b601-894d6e96a211.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BIOLABCAPPS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BIOLABCAPPS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BIOLABCAPPS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: vqalvesmerckcontainerregistry.azurecr.io
          registryUsername: ${{ secrets.BIOLABCAPPS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BIOLABCAPPS_REGISTRY_PASSWORD }}
          containerAppName: biolab-capps
          resourceGroup: vqalves-marck-test-resourcegroup
          imageToBuild: vqalvesmerckcontainerregistry.azurecr.io/biolab-capps:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


